# Solución al Problema XOR con Redes Neuronales
**Código de Estudiante:** 171334

**Apellidos y Nombres:** Godoy Llanqui Erick Renan

**Fecha de Presentación:** 23 / 07 / 2021

**Importar Librerias**
*   Pandas, para crear un dataset referente al operador XOR
*   Numpy, para realizar operaciones con matrices

In [15]:
import numpy as np
import pandas as pd

**Dataframe XOR**

In [16]:
df = pd.DataFrame(
    {
        'X1': [0,0,1,1],
        'X2': [0,1,0,1],
        'Y' : [0,1,1,0]
    }
)
df

X1  X2  Y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

**Separar columnas de entrada y salida**

In [17]:
X = np.array(df[['X1','X2']])
Y = np.array(df[['Y']])

**Mostrar valores de entrada**

In [18]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

**Mostrar valores de salida**

In [19]:
Y

array([[0],
       [1],
       [1],
       [0]])

**Funcion Sigmoide**
*     Función de activación ideal para realizar una clasifiación binaria

$$\frac{1}{1+e^{-x}}$$

In [20]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))

**Función de inicialización donde se especifica el numero de nodos en cada una de las capas y se generan las matrices de los pesos y el bias para la capa oculta y la capa de salida**
*      Nodos en capa de entrada: 2
*      Nodos en capa oculta: 2
*      Nodos en capa de salida: 1

![picture](https://drive.google.com/uc?export=view&id=1k6Q9nZa1RxnyFQ6_6-a-XVxq0hNptGkc)

In [22]:
def init(n_input, n_hidden, n_output):
    pesos_ih = np.random.random((n_hidden, n_input))    #pesos aleatorios con valores entre 0 y 1
    bias_h = np.zeros((n_hidden, 1))                    #bias inicial compuesto por un array de ceros
    
    pesos_ho = np.random.random((n_output, n_hidden))
    bias_o = np.zeros((n_output, 1))
    
    p = {"W1" : pesos_ih, "b1": bias_h,
         "W2" : pesos_ho, "b2": bias_o}

    return p

**Feedforward**
*      Función para realizar propagación hacia adelante

In [23]:
def feedforward(X, Y, p):
    W1 = p["W1"]
    W2 = p["W2"]
    b1 = p["b1"]
    b2 = p["b2"]

    Z1 = np.dot(W1, X) + b1
    A1 = sigmoid(Z1)

    Z2 = np.dot(W2, A1) + b2
    A2 = sigmoid(Z2)

    cache = (Z1, A1, W1, b1, Z2, A2, W2, b2)

    return cache, A2

**Backpropagation**
*     Función para ajustar los valores de los pesos y el bias

In [24]:
def backpropagation(X, Y, cache):
    m = X.shape[1] #Obtener número de filas en X
    (Z1, A1, W1, b1, Z2, A2, W2, b2) = cache
    
    err = A2 - Y   #Calcular tasa de error
    dW2 = np.dot(err, A1.T) / m  #hallar nuevos valores para los pesos en la capa de salida
    db2 = np.sum(err, axis = 1, keepdims=True)  #hallar nuevo valor para el bias en la capa de salida
    
    dA1 = np.dot(W2.T, err) #Multiplicar los pesos de la capa de salida por la tasa de error para los nuevos valores de entrada en la capa oculta

    fp_sigmoid = A1 * (1- A1)  #Emplear la derivada de la función sigmoide sobre los valores de entrada en la capa oculta
    dZ1 = np.multiply(dA1, fp_sigmoid)   #Multiplicar las matrices de los valores de entrada en la capa oculta

    dW1 = np.dot(dZ1, X.T) / m #hallar nuevos valores para los pesos en la capa oculta
    db1 = np.sum(dZ1, axis=1, keepdims=True) / m #hallar nuevo valor para el bias en la capa oculta
    
    dg = {"dZ2": err, "dW2": dW2, "db2": db2,
                 "dZ1": dZ1, "dW1": dW1, "db1": db1}
    return dg

**Actualizar los nuevos valores de los pesos y el bias**

$$W = W - r * p$$

*    Donde:
  
$W = Peso$

$r = tasa - de-aprendizaje$

$ p = pendiente$

In [25]:
def actualizar(p, g, r_aprendizaje):
    p["W1"] = p["W1"] - r_aprendizaje * g["dW1"]
    p["W2"] = p["W2"] - r_aprendizaje * g["dW2"]
    p["b1"] = p["b1"] - r_aprendizaje * g["db1"]
    p["b2"] = p["b2"] - r_aprendizaje * g["db2"]
    return p

**Realizar el entrenamiento de la red neuronal con 100000 epocas**

In [26]:
X = X.T
Y = Y.T

RN = init(2, 2, 1)
ratio_aprendizaje = 0.01

for i in range(100000):
    cache, A2 = feedforward(X, Y, RN)
    grads = backpropagation(X, Y, cache)
    RN = actualizar(RN, grads, ratio_aprendizaje)

**Predecir resultados**

In [39]:
_, A2 = feedforward(X, Y, RN)
pred = (A2 > 0.5) * 1.0     #Redondear valores mayores a 0.5 en 1
print(A2.T)
print("")
print(pred.T)

[[0.0148915 ]
 [0.98484113]
 [0.98490824]
 [0.01680892]]

[[0.]
 [1.]
 [1.]
 [0.]]
